'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, CheckCircle2, Loader2, Network, ShieldCheck } from 'lucide-react'

export default function LenderPage() {
  const [processing, setProcessing] = useState('')
  const act = (name: string) => { setProcessing(name); window.setTimeout(() => setProcessing(''), 1200) }
  return <main className="min-h-screen bg-background text-foreground"><header className="flex min-h-16 items-center justify-between border-b border-border px-5 lg:px-8"><Link href="/dashboard" className="flex items-center gap-3 text-xs font-semibold tracking-[.22em] text-slate-100"><span className="grid h-7 w-7 place-items-center bg-primary text-primary-foreground"><Network size={14}/></span>LEDGERLINE <span className="text-slate-600">/ LENDER</span></Link><Link href="/dashboard" className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.14em] text-slate-500 hover:text-primary"><ArrowLeft size={13}/> Core registry</Link></header><div className="mx-auto max-w-6xl px-5 py-8 lg:px-8"><p className="eyebrow text-primary">LedgerLine / lender workspace</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.05em] text-slate-100">Credit issuance desk</h1><p className="mt-2 font-mono text-[10px] uppercase tracking-[.12em] text-slate-600">Review verified borrower history before committing capital.</p><div className="mt-8 grid gap-px bg-border md:grid-cols-3"><Stat label="Available proofs" value="515"/><Stat label="Verification state" value="ALL VERIFIED"/><Stat label="Environment" value="CC3 / SEPOLIA"/></div><section className="mt-8 border border-border bg-[#060606]"><div className="border-b border-border px-5 py-4"><p className="eyebrow text-slate-500">Lender action queue</p></div><div className="divide-y divide-border">{['Borrower 0x00dC…15f4','Borrower 0x7a91…90c2','Borrower 0x4f12…8b10'].map((item, i) => <div className="flex flex-col gap-4 px-5 py-5 sm:flex-row sm:items-center sm:justify-between" key={item}><div><p className="font-mono text-xs text-slate-300">{item}</p><p className="mt-2 flex items-center gap-2 font-mono text-[10px] uppercase text-primary"><CheckCircle2 size={12}/> Proof continuity verified · score {742 - i * 18}</p></div><button onClick={() => act(item)} disabled={!!processing} className="flex items-center justify-center gap-2 border border-primary/50 px-4 py-2 font-mono text-[10px] uppercase tracking-[.12em] text-primary hover:bg-primary/10 disabled:opacity-60">{processing === item ? <><Loader2 size={12} className="animate-spin"/> Processing</> : <>Review credit <ShieldCheck size={12}/></>}</button></div>)}</div></section></div></main>}
function Stat({label,value}:{label:string,value:string}){return <div className="bg-[#060606] px-5 py-5"><p className="eyebrow text-slate-600">{label}</p><p className="mt-3 font-mono text-sm text-slate-200">{value}</p></div>}
