'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, CheckCircle2, FilePlus2, Loader2, Network } from 'lucide-react'

export default function BorrowerPage() {
  const [processing, setProcessing] = useState(false)
  const register = () => { setProcessing(true); window.setTimeout(() => setProcessing(false), 1400) }
  return <main className="min-h-screen bg-background text-foreground"><header className="flex min-h-16 items-center justify-between border-b border-border px-5 lg:px-8"><Link href="/dashboard" className="flex items-center gap-3 text-xs font-semibold tracking-[.22em] text-slate-100"><span className="grid h-7 w-7 place-items-center bg-primary text-primary-foreground"><Network size={14}/></span>LEDGERLINE <span className="text-slate-600">/ BORROWER</span></Link><Link href="/dashboard" className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.14em] text-slate-500 hover:text-primary"><ArrowLeft size={13}/> Core registry</Link></header><div className="mx-auto max-w-6xl px-5 py-8 lg:px-8"><p className="eyebrow text-primary">LedgerLine / borrower workspace</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.05em] text-slate-100">Credit profile desk</h1><p className="mt-2 font-mono text-[10px] uppercase tracking-[.12em] text-slate-600">Register activity and maintain a portable on-chain credit record.</p><div className="mt-8 grid gap-px bg-border md:grid-cols-3"><Stat label="Current score" value="742"/><Stat label="Verified repayments" value="18"/><Stat label="Profile state" value="CONTINUITY VERIFIED"/></div><section className="mt-8 border border-border bg-[#060606] p-5"><p className="eyebrow text-slate-500">Borrower action desk</p><div className="mt-6 grid gap-4 md:grid-cols-2"><div className="border border-border p-5"><p className="font-mono text-xs text-slate-300">Register new credit activity</p><p className="mt-2 text-sm leading-6 text-slate-500">Create a verifiable loan record on the LedgerLine network for future repayment proofs.</p><button onClick={register} disabled={processing} className="mt-6 flex items-center gap-2 border border-primary/50 px-4 py-3 font-mono text-[10px] uppercase tracking-[.12em] text-primary hover:bg-primary/10 disabled:opacity-60">{processing ? <><Loader2 size={12} className="animate-spin"/> Processing registration</> : <>Register activity <FilePlus2 size={12}/></>}</button></div><div className="border border-border p-5"><p className="font-mono text-xs text-slate-300">Repayment readiness</p><p className="mt-2 flex items-center gap-2 font-mono text-[10px] uppercase text-primary"><CheckCircle2 size={12}/> Token allowance ready</p><p className="mt-4 font-mono text-[10px] leading-5 text-slate-600">Connect a wallet in Core to authorize repayment transactions.</p></div></div></section></div></main>}
function Stat({label,value}:{label:string,value:string}){return <div className="bg-[#060606] px-5 py-5"><p className="eyebrow text-slate-600">{label}</p><p className="mt-3 font-mono text-sm text-slate-200">{value}</p></div>}
