'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, Loader2, Network } from 'lucide-react'
import { Contract, parseUnits } from 'ethers'
import { useWalletContext } from '../../../lib/WalletContext'
import { ADDRESSES, CHAIN_IDS, DEMO_TOKEN, SETTLEMENT_ABI, TOKEN_ABI } from '../../../lib/contracts'
import { TransactionReceipt } from '../../../components/TransactionReceipt'

export default function BorrowerPage() {
  const { address, signer, chainId, connect } = useWalletContext()
  const [loanId, setLoanId] = useState('1'); const [lender, setLender] = useState(''); const [amount, setAmount] = useState('110'); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false); const [txHash, setTxHash] = useState(''); const [txError, setTxError] = useState('')
  async function repay() { setTxHash(''); setTxError(''); if (!signer) return setStatus('Connect wallet first.'); if (chainId !== CHAIN_IDS.sepolia) return setStatus('Switch wallet to Sepolia.'); if (!/^0x[a-fA-F0-9]{40}$/.test(lender)) return setStatus('Enter a valid lender address.'); if (!/^\d+$/.test(loanId) || Number(amount) <= 0) return setStatus('Enter a valid loan ID and positive amount.'); setBusy(true); try { const value = parseUnits(amount, 18); setStatus('Confirm token approval in wallet…'); const token = new Contract(DEMO_TOKEN, TOKEN_ABI, signer); const approval = await token.approve(ADDRESSES.sourceSettlement, value); setTxHash(approval.hash); setStatus('Approval submitted. Waiting for receipt…'); await approval.wait(); setStatus('Approval confirmed. Confirm repayment in wallet…'); const settlement = new Contract(ADDRESSES.sourceSettlement, SETTLEMENT_ABI, signer); const tx = await settlement.repayLoan(loanId, lender, DEMO_TOKEN, value); setTxHash(tx.hash); setStatus('Repayment submitted. Waiting for Sepolia receipt…'); await tx.wait(); setStatus('Repayment confirmed on Sepolia.') } catch (error) { const message = error instanceof Error ? error.message : 'Transaction failed.'; setTxError(message); setStatus(message.includes('user rejected') ? 'Wallet signature rejected.' : 'Repayment failed.') } finally { setBusy(false) } }
  return <main className="min-h-screen overflow-x-hidden bg-background text-foreground"><header className="flex min-h-16 items-center justify-between border-b border-border px-5 lg:px-8"><Link href="/dashboard" className="flex items-center gap-3 text-xs font-semibold tracking-[.22em] text-slate-100"><span className="grid h-7 w-7 place-items-center bg-primary text-primary-foreground"><Network size={14}/></span>LEDGERLINE <span className="text-slate-600">/ BORROWER</span></Link><Link href="/dashboard" className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.14em] text-slate-500 hover:text-primary"><ArrowLeft size={13}/> Core registry</Link></header><div className="mx-auto max-w-5xl px-5 py-10 lg:px-8"><p className="eyebrow text-primary">LedgerLine network / borrower desk</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.05em] text-slate-100">Repay a loan</h1><p className="mt-2 font-mono text-[10px] uppercase tracking-[.12em] text-slate-600">Approve settlement tokens and publish a repayment receipt.</p><section className="mt-8 border border-border bg-[#060606] p-5 sm:p-7"><div className="grid gap-3"><div className="grid gap-3 sm:grid-cols-3"><input value={loanId} onChange={e=>setLoanId(e.target.value)} placeholder="Loan ID" className="border border-border bg-background px-3 py-3 font-mono text-xs"/><input value={lender} onChange={e=>setLender(e.target.value)} placeholder="Lender wallet address" className="border border-border bg-background px-3 py-3 font-mono text-xs sm:col-span-2"/></div><input value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Repayment amount" className="border border-border bg-background px-3 py-3 font-mono text-xs"/><button onClick={async()=>{if(address)return repay();setStatus('Connecting wallet…');try{await connect();setStatus('Wallet connected. Submit the repayment form.')}catch(error){setStatus(error instanceof Error?error.message:'Wallet connection failed.')}}} disabled={busy} className="flex items-center justify-center gap-2 bg-primary px-4 py-3 font-mono text-[10px] uppercase tracking-[.12em] text-primary-foreground disabled:opacity-50">{busy&&<Loader2 size={13} className="animate-spin"/>}{address?'Approve and repay':'Connect wallet'}</button></div>{status&&<p className="mt-4 font-mono text-[10px] text-slate-400" aria-live="polite">{status}</p>}{txHash&&<div className="mt-4"><TransactionReceipt hash={txHash} chain="sepolia" status={busy?'submitted':'confirmed'} label="Repayment transaction" error={txError}/></div>}{txError&&!txHash&&<div className="mt-4"><TransactionReceipt chain="sepolia" status="failed" label="Repayment transaction" error={txError}/></div>}</section></div></main>
}
