'use client'
import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, Loader2, Network } from 'lucide-react'
import { Contract, parseUnits } from 'ethers'
import { useWalletContext } from '../../../lib/WalletContext'
import { ADDRESSES, CHAIN_IDS, DEMO_TOKEN, SETTLEMENT_ABI, TOKEN_ABI } from '../../../lib/contracts'

export default function BorrowerPage() { const { address, signer, chainId, connect } = useWalletContext(); const [loanId,setLoanId]=useState('1'); const [lender,setLender]=useState(''); const [amount,setAmount]=useState('110'); const [status,setStatus]=useState(''); const [busy,setBusy]=useState(false)
  async function repay(){ if(!signer)return setStatus('Connect wallet first.'); if(chainId!==CHAIN_IDS.sepolia)return setStatus('Switch wallet to Sepolia.'); if(!/^0x[a-fA-F0-9]{40}$/.test(lender))return setStatus('Enter a valid lender address.'); if(!/^\d+$/.test(loanId) || Number(amount) <= 0)return setStatus('Enter a valid loan ID and positive amount.'); setBusy(true); try { const value=parseUnits(amount,18); setStatus('Preparing token approval…'); const token=new Contract(DEMO_TOKEN,TOKEN_ABI,signer); setStatus('Confirm token approval in wallet…'); const approval=await token.approve(ADDRESSES.sourceSettlement,value); setStatus(`Approval submitted ${approval.hash.slice(0, 12)}… Waiting for receipt…`); await approval.wait(); setStatus('Approval confirmed. Confirm repayment in wallet…'); const settlement=new Contract(ADDRESSES.sourceSettlement,SETTLEMENT_ABI,signer); const tx=await settlement.repayLoan(loanId,lender,DEMO_TOKEN,value); setStatus(`Repayment submitted ${tx.hash.slice(0, 12)}… Waiting for receipt…`); const receipt=await tx.wait(); setStatus(`Repayment confirmed. Receipt ${receipt.hash.slice(0, 12)}…`) } catch(error){const message=error instanceof Error?error.message:'Transaction failed.'; setStatus(message.includes('user rejected')?'Wallet signature rejected.':message)} finally{setBusy(false)} }
  return <main className="min-h-screen overflow-x-hidden bg-background text-foreground"><header className="flex min-h-16 items-center justify-between border-b border-border px-5 lg:px-8"><Link href="/dashboard" className="flex items-center gap-3 text-xs font-semibold tracking-[.22em] text-slate-100"><span className="grid h-7 w-7 place-items-center bg-primary text-primary-foreground"><Network size={14}/></span>LEDGERLINE <span className="text-slate-600">/ BORROWER</span></Link><Link href="/dashboard" className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.14em] text-slate-500 hover:text-primary"><ArrowLeft size={13}/> Core registry</Link></header><div className="mx-auto max-w-5xl px-5 py-10 lg:px-8"><p className="eyebrow text-primary">LedgerLine network / borrower desk</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.05em] text-slate-100">Repay a loan</h1><p className="mt-2 font-mono text-[10px] uppercase tracking-[.12em] text-slate-600">Approve settlement tokens and publish a repayment receipt.</p><section className="mt-8 border border-border bg-[#060606] p-5 sm:p-7"><div className="grid gap-3"><div className="grid gap-3 sm:grid-cols-3"><input value={loanId} onChange={e=>setLoanId(e.target.value)} placeholder="Loan ID" className="border border-border bg-background px-3 py-3 font-mono text-xs"/><input value={lender} onChange={e=>setLender(e.target.value)} placeholder="Lender wallet address" className="border border-border bg-background px-3 py-3 font-mono text-xs sm:col-span-2"/></div><input value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Repayment amount" className="border border-border bg-background px-3 py-3 font-mono text-xs"/><button onClick={async () => { if (address) return repay(); setStatus('Connecting wallet…'); try { await connect(); setStatus('Wallet connected. Complete the repayment form.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Wallet connection failed.') } }} disabled={busy} className="mt-3 flex items-center justify-center gap-2 border border-primary bg-primary px-4 py-3 font-mono text-[10px] uppercase tracking-[.14em] text-background disabled:opacity-60">{busy&&<Loader2 size={13} className="animate-spin"/>}{busy?'Processing transaction':address?'Approve + repay on LedgerLine':'Connect wallet'}</button>{status&&<p className="mt-4 break-all font-mono text-[10px] leading-5 text-primary">{status}</p>}</div></section></div></main> }
