'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { Contract, JsonRpcProvider } from 'ethers'
import { ArrowRight, Check, ChevronRight, Network } from 'lucide-react'

const RPC = 'https://rpc.cc3-testnet.creditcoin.network'
const REGISTRY = '0xde8365dAF3CFdF952E2F946F19a4DcAcd57eFf0F'
const ABI = ['function getCreditProfile(address) view returns (tuple(uint16 score, uint256 totalVerifiedRepayments, uint256 completedLoanCount, uint256 lastUpdated))']
const SAMPLE = '0x00dC0f3ff1F2bca6b3d007684cC25a766c9815f4'

export default function Page() {
  const [score, setScore] = useState('—')
  useEffect(() => { new Contract(REGISTRY, ABI, new JsonRpcProvider(RPC)).getCreditProfile(SAMPLE).then((p) => setScore(String(p.score))).catch(() => setScore('—')) }, [])
  return <main className="min-h-screen bg-background text-foreground">
    <header className="shell flex min-h-16 items-center justify-between border-b border-border px-5 py-4 lg:px-10"><Link href="/" className="flex items-center gap-3 text-xs font-semibold tracking-[.24em] text-slate-100"><span className="grid h-7 w-7 place-items-center bg-primary text-primary-foreground"><Network size={14}/></span>LEDGERLINE</Link><nav aria-label="LedgerLine navigation" className="hidden items-center gap-6 sm:flex"><Link href="/" className="font-mono text-[10px] uppercase tracking-[.14em] text-slate-100">Home</Link><Link href="/dashboard" className="font-mono text-[10px] uppercase tracking-[.14em] text-slate-500 hover:text-primary">Dashboard</Link><Link href="/dashboard#lender" className="font-mono text-[10px] uppercase tracking-[.14em] text-slate-500 hover:text-primary">Lender</Link><Link href="/dashboard#borrower" className="font-mono text-[10px] uppercase tracking-[.14em] text-slate-500 hover:text-primary">Borrower</Link></nav><Link href="/dashboard" className="flex items-center gap-2 border border-border px-3 py-2 font-mono text-[10px] uppercase tracking-[.16em] text-slate-300 hover:border-primary hover:text-primary">Connect wallet <ArrowRight size={13}/></Link></header>
    <section className="shell grid border-b border-border lg:grid-cols-[1fr_330px]"><div className="border-b border-border px-5 py-16 lg:border-b-0 lg:border-r lg:px-16 lg:py-28"><p className="eyebrow text-primary">Credit infrastructure / registry core</p><h1 className="mt-8 max-w-5xl text-balance text-[4.5rem] font-semibold leading-[.86] tracking-[-.08em] text-slate-100 sm:text-8xl lg:text-[9.5rem]">Proof,<br/><span className="text-primary">as capital.</span></h1><p className="mt-10 max-w-lg text-[15px] leading-7 text-slate-500">LedgerLine converts verified repayment events into portable credit intelligence for institutions operating across chains.</p><Link href="/dashboard" className="mt-10 inline-flex items-center gap-3 bg-primary px-5 py-3 font-mono text-[10px] uppercase tracking-[.16em] text-primary-foreground hover:bg-emerald-300">Enter LedgerLine Core <ChevronRight size={14}/></Link></div><aside className="flex flex-col justify-between bg-[#070707] px-6 py-8 lg:px-8 lg:py-10"><div><p className="eyebrow text-slate-600">Registry signal</p><p className="mt-8 font-mono text-7xl tracking-[-.08em] text-slate-100">{score}</p><p className="mt-2 font-mono text-[10px] uppercase tracking-[.16em] text-slate-600">Live profile score</p></div><div className="border-t border-border pt-6"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.12em] text-primary"><span className="h-1.5 w-1.5 bg-primary"/>CC3 registry online</div><p className="mt-4 font-mono text-[10px] leading-5 text-slate-600">A cryptographic record that travels with the borrower, not the lender.</p></div></aside></section>
    <section className="shell grid border-b border-border sm:grid-cols-3"><Metric value="515" label="Issued proofs"/><Metric value="02" label="Connected environments"/><Metric value="24/24" label="Core tests passing"/></section>
    <section className="shell grid border-b border-border lg:grid-cols-[.7fr_1.3fr]"><div className="border-b border-border px-5 py-12 lg:border-b-0 lg:border-r lg:px-16"><p className="eyebrow text-slate-600">LedgerLine protocol</p><h2 className="mt-5 max-w-sm text-3xl font-semibold leading-tight tracking-[-.05em] text-slate-100">A permanent trail from transaction to trust.</h2></div><div className="bg-[#070707]">{['Receipt decoded','Continuity proof verified','Credit score anchored'].map((item, i) => <div key={item} className="grid grid-cols-[40px_1fr_auto] items-center gap-4 border-b border-border px-5 py-6 last:border-0 lg:px-10"><span className="font-mono text-[10px] text-primary">0{i + 1}</span><div><p className="text-sm text-slate-200">{item}</p><p className="mt-1 font-mono text-[10px] text-slate-600">{['Ethereum Sepolia','Attestcoin Protocol','Creditcoin CC3'][i]}</p></div><Check size={15} className="text-primary"/></div>)}</div></section>
    <footer className="shell flex justify-between px-5 py-6 font-mono text-[10px] uppercase tracking-[.16em] text-slate-700 lg:px-10"><span>LedgerLine Core</span><span>Sepolia / CC3</span></footer>
  </main>
}
function Metric({ value, label }: { value: string; label: string }) { return <div className="border-r border-border px-5 py-7 last:border-r-0 lg:px-10"><p className="font-mono text-3xl tracking-[-.05em] text-slate-100">{value}</p><p className="mt-2 font-mono text-[10px] uppercase tracking-[.14em] text-slate-600">{label}</p></div> }
