'use client'

import Link from 'next/link'
import { ArrowUpRight, Check, ChevronRight, Network } from 'lucide-react'
import { ProductShell } from '../components/ProductShell'

const metrics = [['515', 'Issued credit proofs'], ['02', 'Connected environments'], ['24/24', 'Core tests passing']]

export default function Page() {
  return <ProductShell><section className="grid min-h-[620px] items-center gap-12 border-b border-border px-5 py-16 lg:grid-cols-[1.15fr_.85fr] lg:px-10"><div><p className="eyebrow text-primary">LedgerLine / cross-chain credit infrastructure</p><h1 className="mt-6 max-w-4xl text-5xl font-semibold tracking-[-.065em] text-slate-100 md:text-7xl">Credit history, proven on-chain.</h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-500">LedgerLine gives lenders a portable, verifiable view of repayment behavior across the networks where credit is created.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/credit-profile" className="flex items-center gap-2 bg-primary px-5 py-3 font-mono text-[10px] uppercase tracking-[.12em] text-primary-foreground">Explore credit profile <ArrowUpRight size={14}/></Link><Link href="/verification" className="flex items-center gap-2 border border-border px-5 py-3 font-mono text-[10px] uppercase tracking-[.12em] text-slate-300 hover:border-primary hover:text-primary">View verification layer</Link></div></div><div className="border border-border bg-[#060606] p-5"><div className="flex items-center justify-between border-b border-border pb-4"><span className="eyebrow text-slate-500">LedgerLine network</span><span className="flex items-center gap-2 font-mono text-[10px] text-primary"><i className="h-1.5 w-1.5 rounded-full bg-primary"/>LIVE READ</span></div><div className="mt-8 grid grid-cols-2 gap-px bg-border">{metrics.map(([value, label]) => <div key={label} className="bg-[#060606] p-4"><p className="font-mono text-2xl text-slate-100">{value}</p><p className="mt-2 font-mono text-[9px] uppercase tracking-[.12em] text-slate-600">{label}</p></div>)}</div><div className="mt-5 space-y-3 font-mono text-[10px] text-slate-500"><p><Check className="mr-2 inline text-primary" size={13}/>Sepolia receipt decoded</p><p><Check className="mr-2 inline text-primary" size={13}/>Attestcoin proof verified</p><p><Check className="mr-2 inline text-primary" size={13}/>Credit score anchored</p></div></div></section><section className="grid border-b border-border md:grid-cols-3">{[['Credit Profile','Portable repayment evidence, normalized into one trust surface.','/credit-profile'],['Invoice financing','Turn verified commercial activity into financing eligibility.','/invoices'],['Developer layer','Read proofs and verification states through LedgerLine APIs.','/developers']].map(([title, copy, href]) => <Link key={href} href={href} className="group border-r border-border p-7 last:border-r-0 lg:p-10"><p className="eyebrow text-slate-600">LedgerLine service</p><h2 className="mt-8 text-xl font-medium text-slate-200 group-hover:text-primary">{title}<ChevronRight className="ml-2 inline" size={16}/></h2><p className="mt-3 text-sm leading-6 text-slate-500">{copy}</p></Link>)}</section></ProductShell>
}
